###

GET https://localhost:44324/api/weather-forecast HTTP/1.1

###

GET https://localhost:44324/api/weather-forecast/2 HTTP/1.1

###

GET https://localhost:44301/api/weather-forecast HTTP/1.1

###

GET https://localhost:44301/api/weather-forecast/2 HTTP/1.1
